### ISSUE TITLE
Has this plugin been tested for the newer versions of DuckDB v1.x ?

### ISSUE THREAD

**Issue by ramkumarkb** [cldellow/datasette-parquet#25]
This is a very nice plugin - especially since how much the popularity of DuckDB has grown, since this plugin was first written.

If not, where is likely most of the changes likely to be - to enable a PR.

Thank you!

**Comment by cldellow** [comment]
No idea! The best path is probably to upgrade and see what happens. If there's an issue that you're unable to debug, if you report it here I can try to point you in the right direction.

Note that I'm not currently focused on this plugin, so any respond will be best effort on my part.

**Comment by Alexandre-Herve** [comment]
Hey there, I'm using duckdb version `v1.2.0` and datasette version `1.0a17` with datasette-parquet version `0.6.1`. 

After running `datasette --metadata metadata.json` with the metadata file pointing to my duckdb database, I get the error below upon opening the page.
The error seems to come from [this line](https://github.com/simonw/datasette/blob/209bdee0e8d1b578c48fe6dbc2e51739dc1d1f0a/datasette/database.py#L510) in the datasette codebase.

I would attempt a patch but I have no idea where to look at. Any guidance?

Thanks!

```
CatalogException: Catalog Error: Table with name pragma_table_list does not exist!
Did you mean "pragma_database_list"?

LINE 1: WITH shadow_tables AS (SELECT name FROM pragma_table_list WHERE "type" = 'shadow' ORDER BY name...
                                                ^
Traceback (most recent call last):
  File "/pasteur/zeus/projets/p01/MDM/MDM_conda/mdm_ah/lib/python3.12/site-packages/datasette/app.py", line 1768, in route_path
    response = await view(request, send)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pasteur/zeus/projets/p01/MDM/MDM_conda/mdm_ah/lib/python3.12/site-packages/datasette/views/base.py", line 180, in view
    return await self.dispatch_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pasteur/zeus/projets/p01/MDM/MDM_conda/mdm_ah/lib/python3.12/site-packages/datasette/views/base.py", line 134, in dispatch_request
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/pasteur/zeus/projets/p01/MDM/MDM_conda/mdm_ah/lib/python3.12/site-packages/datasette/views/index.py", line 39, in get
    hidden_table_names = set(await db.hidden_table_names())
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pasteur/zeus/projets/p01/MDM/MDM_conda/mdm_ah/lib/python3.12/site-packages/datasette/database.py", line 508, in hidden_table_names
    for x in await self.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/pasteur/zeus/projets/p01/MDM/MDM_conda/mdm_ah/lib/python3.12/site-packages/datasette/database.py", line 345, in execute
    results = await self.execute_fn(sql_operation_in_thread)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pasteur/zeus/projets/p01/MDM/MDM_conda/mdm_ah/lib/python3.12/site-packages/datasette_parquet/ducky.py", line 88, in execute_fn
    return await asyncio.get_event_loop().run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pasteur/zeus/projets/p01/MDM/MDM_conda/mdm_ah/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pasteur/zeus/projets/p01/MDM/MDM_conda/mdm_ah/lib/python3.12/site-packages/datasette_parquet/ducky.py", line 86, in in_thread
    return fn(self.conn)
           ^^^^^^^^^^^^^
  File "/pasteur/zeus/projets/p01/MDM/MDM_conda/mdm_ah/lib/python3.12/site-packages/datasette/database.py", line 315, in sql_operation_in_thread
    cursor.execute(sql, params if params is not None else {})
  File "/pasteur/zeus/projets/p01/MDM/MDM_conda/mdm_ah/lib/python3.12/site-packages/datasette_parquet/winging_it.py", line 94, in execute
    rv = self.cursor.execute(sql, parameters)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.CatalogException: Catalog Error: Table with name pragma_table_list does not exist!
Did you mean "pragma_database_list"?

LINE 1: WITH shadow_tables AS (SELECT name FROM pragma_table_list WHERE "type" = 'shadow' ORDER BY name...
```
